---
title: "Maximum Mean Discrepancy"
subtitle: ""
author: "Frederick Boehm"
institute: ""
date: "March 11, 2021 (updated: `r Sys.Date()`)"
bibliography: mmd.bib
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r, load_refs, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE,
           bib.style = "authoryear",
           cite.style = "alphabetic",
           style = "markdown",
           hyperlink = FALSE,
           dashed = FALSE)
bib <- ReadBib("mmd.bib", check = FALSE)
```


## Maximum Mean Discrepancy: What is it? 

- Statistical method for inferring whether two samples have distinct underlying distributions `r Citep(bib, "gretton2012kernel")`

- Idea: 



---

## Software implementations

- R package `EasyMMD`: https://github.com/AnthonyEbert/EasyMMD/blob/master/R/mmd.R


---

## References

```{r refs, echo=FALSE, results="asis"}
PrintBibliography(bib)
```



---

class: center, middle

# Thanks!

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

